### ISSUE TITLE
Error on walk() with returned Sequence

### ISSUE THREAD

**Issue by manuelito02** [markreidvfx/pyaaf2#100]
Hi there!

I'm pretty new to AAF and pyaaf and I'm not sure if the aaf file that I'm trying to read is messy. But I get following error when trying to open it with OTIO (but the error comes from pyaaf2):

```
  File "/uvfx/Homes/cgiesa/venv/lib/python2.7/site-packages/aaf2/components.py", line 206, in walk
    type(segment)))
NotImplementedError: Sequence returned <class 'aaf2.components.Sequence'> not implemented
```

Greets,
Carlo

**Comment by markreidvfx** [comment]
see #35 OTIO is working on a better solution.

**Comment by manuelito02** [comment]
Hi Mark!
Thanks for your feedback. I'll see then what OTIO will come up with.
Greets,
Carlo
