### ISSUE TITLE
Confused on how to add a new track

### ISSUE THREAD

**Issue by necropolis999** [markreidvfx/pyaaf2#104]
Just that. I have several wav files that I need to import to different tracks, several wavs on each track. All the examples I've encountered either fail, involve video tracks, or muddy the waters by being well beyond the scope of what I'm trying to do.

**Comment by necropolis999** [comment]
Figured it out, sorry

**Comment by bleachcult** [comment]
@necropolis999 Could you please share how you managed to solve the issue of creating new audio tracks? I've not found many useful examples on this either. Thanks.

**Comment by necropolis999** [comment]
this is the script i made. it has some extra stuff in there, but you should
be able to glean what you need from it

'''Script for creating an aaf file from a list of wav files'''
import json
import logging
import re
import subprocess
import sys
import aaf2
import os
from collections import OrderedDict

logging.basicConfig(filename='script.log', filemode='w')

with aaf2.open(sys.argv[1], 'w') as file:
    comp = file.create.CompositionMob("the_composition")
    file.content.mobs.append(comp)
    tcs = comp.create_empty_sequence_slot(25, media_kind='Timecode')
    tcc = file.create.Timecode(25, drop=False)
    tcs.segment.components.append(tcc)
    comp.usage = 'Usage_TopLevel'
    START_TIME = 0
    EDIT_RATE = 25
    track_numbers = OrderedDict()
    clips = []

    # get arguments
    for x in range(2, len(sys.argv) - 2, 3):
        try:
            start = int(float(sys.argv[x+1]) * EDIT_RATE)
        except ValueError:
            logging.error('Parameter %s is not a number', sys.argv[x+1])
            sys.exit('Invalid parameter')
        try:
            duration = int(float(sys.argv[x+2]) * EDIT_RATE)
        except ValueError:
            logging.error('Parameter %s is not a number', sys.argv[x+2])
            sys.exit('Invalid parameter')
        head, tail = os.path.split(sys.argv[x])
        clips.append({'path': sys.argv[x], 'name': tail, 'start': start,
'duration': duration})

    # determine number of tracks based on system args
    for arg in clips:
        try:
            track = arg['name'].split('_', 1)[1]
        except IndexError:
            logging.error('Parameter %s does not have a track value',
arg['name'])
            sys.exit('Invalid parameter')
        track_numbers.setdefault(track, [])
        track_numbers[track].append(arg['name'])

    # create a track for each
    tracks = OrderedDict()
    for track_number in track_numbers:
        tracks[track_number] = comp.create_sound_slot(EDIT_RATE)
        tracks[track_number].name = track_number

    # cycle through files
    for arg in clips:
        track = arg['name'].split('_', 1)[1]
        name = arg['name'].split('_', 1)[0]

        master = file.create.MasterMob(name)
        file.content.mobs.append(master)
        master.import_audio_essence(arg['path'], EDIT_RATE)
        clip = master.create_source_clip(slot_id=1, start=arg['start'],
length=arg['duration'])

        source = file.create.SourceMob()
        file.content.mobs.append(source)
        source.create_tape_slots(name, EDIT_RATE, arg['start'],
media_kind='sound')

        tracks[track].segment.components.append(clip)

        # add fillers on other tracks
        for key, value in tracks.items():
            if key != track:
                filler = file.create.Filler('sound', arg['duration'])
                value.segment.components.append(filler)

**Comment by bleachcult** [comment]
Many thanks for this example.
