### ISSUE TITLE
packing signed/unsigned

### ISSUE THREAD

**Issue by kkoutso** [markreidvfx/pyaaf2#119]
Hello, 

I came across a case of a set of MXF files that where it seems that there is negative StartTime.
The issue is that when this value (18446744073709551614 if packed as unsigned, otherwise it is -2 if packed as unsigned) is processed in src/aaf2/types.py during encoding (line 126):
`    def encode(self, value):
        return pack(self.pack_format(), value)
`
the pack_format (although self.signed is true) makes it lowercase (line 116):
`        if self.signed:
            fmt = fmt.lower()
`
this causes struct.error: argument out of range
Modifying 116:
`        if not  self.signed:
            fmt = fmt.lower()
`
allows the processing to complete.

I am not sure whether this is bug or my MXFs are somewhat faulty, but I will appreciate any feedback.

Thanks for the great work.

Kostas

**Comment by markreidvfx** [comment]
without an MXF sample there isn't much anyone can do to help. please reopen if you can supply one.
