### ISSUE TITLE
How to Create an Avid Captions Only AAF

### ISSUE THREAD

**Issue by ndeshpande2022** [markreidvfx/pyaaf2#135]
Hi there,

I'm looking for information on how to create an Avid Captions Only AAF.

My thought was to create an MXF with embedded 608/708 captions and then use pyAAF to wrap the MXF. This doesn't seem to be working. Any thoughts/tips/hints?

Very much appreciated. I would be happy to post back a full solution once I find one. 

Thank you

**Comment by TrevorAyl** [comment]
Are you talking about captions in a data track? Rather than SubCap titles (which would be easier as a .txt or .STL file).

**Comment by ndeshpande2022** [comment]
Hi @TrevorAyl,

We did a little work on and this found that we needed to create an MXF file with the 436 ANC Data track. We did this using the BMX project from the BBC (specifically raw2bmx.exe).

We then used pyaaf2 to link the external MXF file to the AAF. This worked great, however we needed to update one of the function lines to allow for non-op1a mxf's to be linked. This was an easy change to make. 

I think we can close this ticket since it's not pyAAF's job to make the MXF file... unless that's something it can do/could do in the future.

**Comment by ndeshpande2022** [comment]
@TrevorAyl I wanted to follow up because you may have more experience working with this pyAAF. The AAF files we've created still require the MXF file to be present. Is there a way to embed the MXF file in the AAF instead of just linking it?

**Comment by TrevorAyl** [comment]
> @TrevorAyl I wanted to follow up because you may have more experience working with this pyAAF. The AAF files we've created still require the MXF file to be present. Is there a way to embed the MXF file in the AAF instead of just linking it?

Sorry I don't have the experience for that I'm afraid.

**Comment by ndeshpande2022** [comment]
No worries - thanks again.
