### ISSUE TITLE
Example request

### ISSUE THREAD

**Issue by will-riley** [markreidvfx/pyaaf2#2]
Successfully ran the example in the docs, and I'm wondering if you could show an example of placing multiple audio clips at various TC addresses in a single track. Trying to grasp the right syntax relative to the AAF object spec...Thanks

**Comment by markreidvfx** [comment]
Hi @will-riley, thanks for giving pyaaf2 a try! Could you provide sample aaf file of what you are trying to match?  Dumping that file will give you the structure and a good starting point. 

Unfortunately I haven't yet ported over the examples and tests from [pyaaf1](https://github.com/markreidvfx/pyaaf), there might be something helpful there, and the api is similar.

**Comment by will-riley** [comment]
pyaaf1 dump.py and qt_aafmodel.py both worked for me using pyaaf2, and are definitely helpful - I can see the object relationships now, thanks for that. Walked through your examples and it's getting clearer, but appending new objects in the right positions is a bit of a puzzle atm. Here's the file I'm trying to make - Thanks!

[aaf_2trks_4clips.aaf.zip](https://github.com/markreidvfx/pyaaf2/files/1629382/aaf_2trks_4clips.aaf.zip)

**Comment by markreidvfx** [comment]
Thanks for the file, I'll take a look. pyaaf2 cannot read the file, It appears your AAF file with 512 sector size (everything I've bee working with has been 4096 sector size),  I've been looking for one, would I be able to use your file in test suit?

**Comment by will-riley** [comment]
Absolutely!

**Comment by markreidvfx** [comment]
okay well pyaaf2 can now read you file, back to your issue!
a Sequence is made of components, which are sourceclips/filler/effects etc.
To place a component at particular edit position the sum of lengths of the previous components need  add up to that  edit position.

the following will add a "New" composition to your aaf file and place a different clip every 100 edit units separated by 100 units of filler. then dumps the edit position of each sourceclip.

```
with aaf2.open("aaf_2trks_4clips.aaf", 'rw') as f:
    edit_rate = 25
    c = f.create.CompositionMob("New")
    f.content.mobs.append(c)
    track1 = c.create_sound_slot(edit_rate)

    for mob in f.content.mastermobs():
        length = 100
        start = 0
        slot_id = 3
        filler = f.create.Filler('sound', length)
        audio_clip =  mob.create_source_clip(slot_id, start, length)
        track1.segment.components.append(filler)
        track1.segment.components.append(audio_clip)

    # dump the edit postion of every sourceclip
    edit_pos = 0
    for item in track1.segment.components:
        if isinstance(item, aaf2.components.SourceClip):
            print item.mob.name, "at", edit_pos

        edit_pos += item.length
```
![screen shot 2018-01-17 at 7 51 50 pm](https://user-images.githubusercontent.com/814966/35080032-ed65f7ec-fbbf-11e7-8940-d8e60a99676d.png)

does that help?

**Comment by will-riley** [comment]
The appended clips don't show up in Pro Tools. Seems PT likes to have SourceClips inside an OperationGroup?

![op_grp](https://user-images.githubusercontent.com/8586358/35191544-87508844-fe32-11e7-8d34-e65f2143a836.png)

**Comment by will-riley** [comment]
Trying to get audio_clip "inside" the OperationGroup. Not succeeding yet.
Unsure how the OperationDef should be defined (just used the uuid for gain to test),
or how to fold in the source clip...thanks!
~~~~
for mob in f.content.mastermobs():
        length = 100
        start = 0
        slot_id = 3
        filler = f.create.Filler('sound', length)
        audio_clip =  mob.create_source_clip(slot_id, start, length)
        opDef = f.create.OperationDef('9d2ea894-0968-11d3-8a38-0050040ef7d2')
        group = f.create.OperationGroup(opDef)
        #group.append(audio_clip) #no append method
        track1.segment.components.append(group)
        track1.segment.components.append(filler)
~~~~

**Comment by markreidvfx** [comment]
Use f.dictionary.lookup_operationdef() to get whatever one you need. See #3. If the operationdef isn't there you need to construct it and it's parameters and register it in the f.dictionary
