### ISSUE TITLE
WAVEDescriptor implementation/PR

### ISSUE THREAD

**Issue by iluvcapra** [markreidvfx/pyaaf2#23]
Hi there, I've been playing around with AAFs for Pro Tools like @will-riley in  #2 , and I have working code for creating useable MOBs for linking to WAV files through WAVDescriptors. I had the thought of submitting this as a PR, would you like that and how exactly would you like the interface to look?

**Comment by markreidvfx** [comment]
Hi @iluvcapra! Thanks for trying out pyaaf2.  I'm more then happy to accept a pull request. If I have issues with the code, we can discuss on the pull request and go from there.  Is this a waveDescrptor class? Just make sure to match the style of the existing code and it should be easy to get merged!

**Comment by iluvcapra** [comment]
Okay, let me figure it out.
