### ISSUE TITLE
Can't read AAF

### ISSUE THREAD

**Issue by samsamm777** [markreidvfx/pyaaf2#29]
The read AAF example doesn't seem to work for me, with no discernible errors.

```
import aaf2

with aaf2.open("my_aaf.aaf", "r") as f:

    # get the main composition
    main_compostion = next(f.content.toplevel())

    # print the name of the composition
    print(main_compostion.name)

    # AAFObjects have properties that can be
    # accessed just like a dictionary
    print(main_compostion['CreationTime'].value)

    # video, audio and other track types are
    # stored in slots on a mob object.
    for slot in main_compostion.slots:
        segment = slot.segment
        print(segment)
```

```$ python read.py
Traceback (most recent call last):
  File "read.py", line 8, in <module>
    main_compostion = next(f.content.toplevel())
StopIteration
```

**Comment by markreidvfx** [comment]
Your AAF might not have a toplevel composition, which is possible, thats might be whats going on. Are you able to share the aaf?

**Comment by samsamm777** [comment]
I cant share this one, but i will make another one the same way. Is it 'normal' to not have a top level composition?

**Comment by markreidvfx** [comment]
There  is no rule that says a AAF needs to have any toplevel CompositionMobs. A file can just be a bunch MasterMobs, it depends on what you select when you export from Avid.  The example assumes  you selected a Sequences in Avid and exported a AAF.
