### ISSUE TITLE
trying to migrate from pyaaf -questions

### ISSUE THREAD

**Issue by ding-hub** [markreidvfx/pyaaf2#3]
I'm trying to migrate from pyaaf but since you are trying to do thing a bit different with this version I am not sure how to do a few things. The first one is trying to create a custom OpDef. Here is how I'm doing it in pyaaf. I can't seem to figure out how to do it in this version.
```
    # CREATE PARAMETER AVIDEFFECTID DEFINITION
    typedef = f.dictionary.lookup_typedef("Rational")
    param = aaf.define.ParameterDef(f, parmID, "AvidEffectID", "avid effect id", typedef)
    f.dictionary.register_def(param)

    # CREATE MATTE KEY DEFINITION
    op_def = aaf.define.OperationDef(f, effectID, "MatteKey_2", "matte key def")
    op_def.media_kind = "picture"
    op_def['IsTimeWarp'].value = "False"
    op_def['Bypass'].value = 2
    op_def['NumberInputs'].value = 3
    op_def['OperationCategory'].value = "OperationCategory_Effect"

    f.dictionary.register_def(op_def)

    # Added Parameter Definition to Operation Definition
    op_def.add_parameterdef(param)

    # CREATE OPERATION GROUP
    opgroup = aaf.component.OperationGroup(f, "picture", length, op_def)
```

Second thing is how do you add comments. Here is the code from pyaaf.

```
 if attributes:
        for attribute, content in attributes.items():
            mastermob.append_comment(attribute, content)
```

Thanks

**Comment by markreidvfx** [comment]
hi @ding-hub your first example should work now in latest master
try this:
```
typedef = f.dictionary.lookup_typedef("Rational")
param = f.create.ParameterDef(parm_id, "AvidEffectID", "avid effect id", typedef)
f.dictionary.register_def(param)

op_def = f.create.OperationDef(effect_id, "MatteKey_2", "matte key def")
op_def.media_kind = "Picture"
f.dictionary.register_def(op_def)
op_def['IsTimeWarp'].value = False
op_def['Bypass'].value = 2
op_def['NumberInputs'].value = 3
op_def['OperationCategory'].value = "OperationCategory_Effect"
op_def['ParametersDefined'].append(param)

length = 100
operation = f.create.OperationGroup(op_def, length)

mob = f.create.MasterMob()
f.content.mobs.append(mob)
slot = mob.create_picture_slot()
slot.segment.components.append(operation)
```
you can also look at test_dictionary.py

As for comments, currently I have a helper on the mob class, its still rough but you can
try this:
```
mob = f.create.MasterMob()
mob.comments['comment'] = 'value'
```

you also asked earlier about new_phys_source_ref and linking mxfs
pyaaf2 has a small mxf parser so I'm hoping it should now be as simple as
```
f.content.link_external_mxf("/path/to/file.mxf")
```

but if you want to replicate new_phys_source_ref  
try this:
```
clip = sourcemob.create_source_clip(slot_id=1, length=length)
slot = mastermob.create_picture_slot(edit_rate)
slot.segment.components.append(clip)
```

**Comment by ding-hub** [comment]
Thanks, I'm almost there but I also noticed there is no insert on the operation group. This is what I was doing in pyaaf
```
# CREATE NESTED SCOPE FOR ALPHA CHANNEL EFFECT
    scopesequence = f.create.Sequence("picture")
    opgroup.insert(0, scopesequence)
    scope = f.create.Filler("picture", length)
    scopesequence.append(scope)

    opgroup.insert(1, composite["(Source)"])
    opgroup.insert(2, composite["(Alpha)"])

    timeline_slot = f.create.TimelineMobSlot()
    timeline_slot.editrate = rate
    timeline_slot.name = "Matte Key: " + output_name + " (Alpha)"
    timeline_slot.segment = opgroup
    comp_mob.append_slot(timeline_slot)
```

**Comment by markreidvfx** [comment]
all array properties should have a insert method, try instead
```
opgroup['InputSegments'].insert(0, scopesequence)
```

**Comment by ding-hub** [comment]
So to append a slot in a comp mob I would do this...
`comp_mob['Slots'].append(timeline_slot)`

**Comment by markreidvfx** [comment]
Yes, that will work. Mobs also have a convenience property
So this will work too
```
comp_mob.slots.append(timeline_slot)
```
But it's exactly the same

**Comment by ding-hub** [comment]
About you question. The reason I'm not using link external is because I want to add a tape name, make sure to flag the mxf as drop frame and add the clip to an operation group so I figured for something like that I would have to do it manually. I used your create sequence example and just added the file package umid of the mxf to the source mob.

**Comment by markreidvfx** [comment]
Well whatever works! Just wanted to let you know the is a mxf file parser is included.  Another  thing you might need to be careful with is the effect_id and parameter_ids you are using, pyaaf2 is using the UUID class for all labels. But pyaaf1 might display them half-swapped if  they are certain types,  if avid doesn't complain then you probably don't have a problem.
