### ISSUE TITLE
Extracting Image Data

### ISSUE THREAD

**Issue by samsamm777** [markreidvfx/pyaaf2#31]
Im trying to get access to embedded images inside an AAF. Is it possible to read the 'Picture' data on a SourceClip?

Here is my mess for some guidance...
```
import aaf2

with aaf2.open("my.aaf", "r") as f:
    for mob in f.content.mobs:
        print(mob.name, mob.usage, mob.comments)
        for slot in mob.slots:
            print(slot)
            print(slot.edit_rate)
            print(slot.origin)
            segment = slot.segment
            print(segment)
            print(segment.start)
            print(segment.media_kind)
```

```
➜  pythontest python read.py
(None, None, <aaf2.misc.TaggedValueHelper object at 0x105f3e7d0>)
<aaf2.mobslots.TimelineMobSlot 1 "Test" at 0x105f39520>
24
0
<aaf2.components.SourceClip SourceClip at 0x105a06d60>
0
Picture
(u'??????', None, <aaf2.misc.TaggedValueHelper object at 0x105e64d10>)
<aaf2.mobslots.TimelineMobSlot 1 "A Slot" at 0x105f39af8>
24
0
<aaf2.components.SourceClip SourceClip at 0x105f39b50>
0
Picture
```

**Comment by markreidvfx** [comment]
Embed data is stored on `EssenceData` objects in `f.content.essencedata`  Their mob_id match their corresponding `SourceMob`.  You can also get the `EssenceData` from a helper `SourceMob.essence`  too.  To read the data on in a `EssenceData` object use `EssenceData.open`. It will return a file like `Stream` object that has read/write methods.

**Comment by markreidvfx** [comment]
The corresponding `SourceMob.descriptor` describes what the essence data is. There is a helper method for export pcm audio as a wav file. Video is commonly the raw dnxhd stream or uncompressed yuv/RGB/alpha depending on the descriptor.
