### ISSUE TITLE
component_at_time is missing

### ISSUE THREAD

**Issue by freesonluxo** [markreidvfx/pyaaf2#32]
Hi there Mark.

Our implementation of `walk()` calls a function called component_at_time. It'd be great to have this functionality back. See the commented lines here...

Do you think we can get this implemented? Thank you!

```
def _walk_item(thing):
    slot = thing.slot
    if not slot:
        return
    segment = slot.segment
    if isinstance(segment, aaf2.components.SourceClip):
        yield segment
        for item in _walk_item(segment):
            yield item
    # elif isinstance(segment, aaf2.components.Sequence):
    #     clip = segment.component_at_time(thing.start_time)
    #     if isinstance(clip, SourceClip):
    #         yield clip
    #         for item in clip._walk_item():
    #             yield item
    #     else:
    #         raise NotImplementedError(
    #            "Sequence returned {} not implemented".format(type(segment))
    elif isinstance(segment, aaf2.components.EssenceGroup):
        yield segment
    elif isinstance(segment, aaf2.components.Filler):
        yield segment
    else:
        raise NotImplementedError(
            "walking {} not implemented".format(type(segment))
)
```

**Comment by markreidvfx** [comment]
Yes will add, it shouldn't be hard, its implemented mostly in python code in pyaaf1
https://github.com/markreidvfx/pyaaf/blob/master/aaf/component/Sequence.pyx#L46

**Comment by ssteinbach** [comment]
Hey Mark, this has come up again for us recently.  Is there anything we can do to help this along?  Thanks!

**Comment by markreidvfx** [comment]
`component_at_time` is now implemented in the latest master.

**Comment by ssteinbach** [comment]
Awesome, thanks Mark!  We'll take a look.

FWIW this is the code block where we're hitting it: 
https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/f9ae17cda3e93eb4753e957e82801b06f07ed547/opentimelineio_contrib/adapters/advanced_authoring_format.py#L65
