### ISSUE TITLE
link_external_mxf doesn't work for audio-only mxf files

### ISSUE THREAD

**Issue by pixelrebel** [markreidvfx/pyaaf2#4]
I'm trying to link mxf wrapped PCM audio streams.  I've tried using aaf2's built-in method `link_external_mxf` and also pyaaf's example [link_external_mxf.py](https://github.com/markreidvfx/pyaaf/blob/master/example/link_external_mxf.py), but it only seems to work for video files.  How would I link audio mxf files similar to video mxf files?

**Comment by markreidvfx** [comment]
Could you provide a sample MXF file that won't link? Make sure the MXF is in "Avid MediaFiles"  when you import it so avid can see it. Sometimes avid won't show it too unless you close and reopen the bin.

**Comment by pixelrebel** [comment]
I probably can't get permission to post it.  I'm sure I'm doing something wrong.  Perhaps I should take a step back and try to describe what I am doing?

I have a single recorded clip delivered to me as separate OpAtom mxf files: one video file and eight audio files. I would like to combine these into a single AAF for easy import into an NLE.  Am I on the right track (no pun intended)?  

There is plenty of good metadata in the mxf files.  In fact, I can probably build the AAF file I need from just the video MXF file.  It contains all the metadata for the audio tracks too!   But, when I link the external video mxf with pyaaf and import into Avid or Premiere, the metadata is wrong, it includes a single audio track and the media doesn't link.

**Comment by markreidvfx** [comment]
OpAtom makes a pretty tangle mess. Each file should have the same MaterialPackageID but also reference the FilePackageIDs in the the other files.  link_external_mxf does exactly what your describing. If your run it on all your files, it should create 1 masterMob that links to 8 sourceMobs (then each sourcemob might then link to the same tapemob). but it quite possible there might be bugs in my MXF parser!

here how to dump the metadata
```
from aaf2 import mxf
import sys
path = sys.argv[1]
f = mxf.MXFFile(path)
f.dump()
```
would you be able to share metadata dumps of them?

**Comment by pixelrebel** [comment]
Ah, your dump script helped me understand why the link wasn't working properly.  The examples I was given had separate clip names for the audio and video files!    I got a new example set from editorial and your library worked like a charm!  Thanks @markreidvfx!
