### ISSUE TITLE
MarkIn-MarkOut

### ISSUE THREAD

**Issue by bcvery1** [markreidvfx/pyaaf2#45]
I'm trying to set MarkIn and MarkOut points on imported dnxhd essence.

Here's what is not working:
```python
master_mob = f.create.MasterMob()
slot = master_mob.import_dnxhd_essence("sample.dnxhd", 24)
slot['MarkIn'].value = 1
f.content.mobs.append(master_mob)
```

How should I be doing this?

**Comment by markreidvfx** [comment]
setting `slot['MarkIn'].value`  and `slot["MarkOut"].value` seem to work for me. 
your talking about this right?

![image](https://user-images.githubusercontent.com/814966/55208371-4f13f700-519b-11e9-8d9d-5e02df19ca4f.png)

**Comment by bcvery1** [comment]
I must have made a mistake in my testing - this is working as expected.  Many thanks
