### ISSUE TITLE
The audio file in AAF does't showed in Protools

### ISSUE THREAD

**Issue by yedianyang** [markreidvfx/pyaaf2#46]
Firstly, Thank you for your resource.

I am trying to learn how to put audio file by  code. I follow the Quickstart "Embedding Footage" part to embed a wav file into the aaf. But when I import that aaf into Protools, the audio file doesn't show up. It just become a block on the track. But the size of the aaf seems contain the wav.

here is the screenshot.
![image](https://user-images.githubusercontent.com/26264896/55209508-fe91ad80-521d-11e9-9c16-587709c12ae1.png)

`
import aaf2

with aaf2.open("example2.aaf", 'w') as f:

    # objects are create with a factory
    # on the AAFFile Object
    mob = f.create.MasterMob("Demo2")

    # add the mob to the file
    f.content.mobs.append(mob)

    edit_rate = 25

    # lets also create a tape so we can add timecode (optional)
    tape_mob = f.create.SourceMob()
    f.content.mobs.append(tape_mob)

    timecode_rate = 25
    start_time = timecode_rate * 60 * 60 # 1 hour
    tape_name = "Demo Tape"

    # add tape slots to tape mob
    tape_mob.create_tape_slots(tape_name, edit_rate,
                               timecode_rate, media_kind='picture')

    # create sourceclip that references timecode
    tape_clip = tape_mob.create_source_clip(1, start_time)

    # now finally import the generated media
    #mob.import_dnxhd_essence("sample.dnxhd", edit_rate, tape_clip)
    mob.import_audio_essence("/Users/yedianyang/Desktop/AD_001.wav", edit_rate)
`

**Comment by ele-wildersheep** [comment]
And I have been trying to construct hierarchical structure like the this
![image](https://user-images.githubusercontent.com/26264896/55209595-6cd67000-521e-11e9-84e5-9035cf73ed86.png)

`import aaf2

with aaf2.open("example2.aaf", 'w') as f:

    # objects are create with a factory
    # on the AAFFile Object
    mob = f.create.MasterMob("Footstep")

    # add the mob to the file
    f.content.mobs.append(mob)
    
    file_sourcemob = f.create.SourceMob()
    f.content.mobs.append(file_sourcemob)
    
    
    edit_rate = 30
    timecode_rate = 30
    start_time = timecode_rate * 60 * 60 # 1 hour
    tape_name = "Demo Tape"

    
    file_sourcemob.create_timeline_slot(edit_rate)
    file_sourcemob.create_empty_sequence_slot(edit_rate)
    
    
    sound_clip = file_sourcemob.create_sound_slot(edit_rate)

    # now finally import the generated media
    
    file_sourcemob.import_audio_essence("/Users/yedianyang/Desktop/GALA/AD_001.WAV", edit_rate)


#it will warn
#ValueError: slot id: 1 already exists
`

**Comment by markreidvfx** [comment]
Have you looked at #37? I don't have access to protools and am not too familiar with it. Does it support embedded media?

**Comment by ele-wildersheep** [comment]
> Have you looked at #37? I don't have access to protools and am not too familiar with it. Does it support embedded media?

Thank you! That help me a lot!
But there is still a problem confuse me. After I append the source_clip to the Sequence, how can I import a essence audio into the AAF, and link to the source_clip?

**Comment by markreidvfx** [comment]
Try using the `import_audio_essence` method on the mastermob like in the embedding example.  Then create your sourceclips of the `MasterMob` and add them to a sequence on the slots of a CompositionMob. Hope that makes sense!
