### ISSUE TITLE
Mix and match embedded and already imported media in AAF

### ISSUE THREAD

**Issue by kevinparkbss** [markreidvfx/pyaaf2#47]
Hi Mark!

I was hoping you might be able to point me in the right direction. I'm having success embedding media into aaf's to load into the avid. This works great if all the clips in the sequence are new versions that the avid hasn't imported before. What I'm hoping to do is mix and match new embedded media as well as clips that link to already imported clips in the avid without having to import that media again.

If I wanted to specify that a clip is already in the avid and have it link to that media in the timeline, how should I go about doing that in pyaaf2?

Thanks again for all your help and an amazing resource!

**Comment by markreidvfx** [comment]
there are probably a couple ways to do it depending on your workflow.

if you know the locations of the mxf files you can use link to external mxf like this

```python
import aaf2
with aaf2.open(out_file, 'w') as f:
    path = "/path/to/file.mxf"
    mobs =  f.content.link_external_mxf(path)
```

you could also modify a aaf exported from avid already containing the the clips need.

**Comment by kevinparkbss** [comment]
thanks mark!
If we implement a workflow that creates individual shot aaf's, would it be possible to generate a sequence level aaf that references those individual shot aaf's so they link up in the avid? Perhaps by referencing MobID's? Instead of using mxf paths, modifying an existing aaf, or importing dnxhd essence? Thanks!

**Comment by markreidvfx** [comment]
Using the same MobIDs would source the same media and avid should link to the right media without a path. But I don't if avid will use the same MasterMobs especially if the clips are in another bin from the one your importing into. You'd have to test, if a AAF exported for avid can do what your describing then it should be able to do with pyaaf.
.

**Comment by kevinparkbss** [comment]
When I compare importing a single clip aaf into the avid and export out a sequence aaf of that clip from the avid, I think they are sharing the same mastermobs, or at least passing them through but that's not enough to create essence data in the pyaaf2 generated aaf, which the Avid needs to figure out the track make up of the master clip. I'll keep plugging away. The external mxf path would be a fine way to work but the issue is that our nexis storage for the avid isn't connected directly to our network. Thanks!

**Comment by kevinparkbss** [comment]
Perhaps I can ama link previously imported quicktimes in the aaf generator? It would come in offline but a simple relink based on clip or tape name inside the avid would bring them online, I'm presuming. I would have to look into ama linking clips in an aaf since I've never done that before but in theory this should work right?
