### ISSUE TITLE
Null or invalid characters in some string values

### ISSUE THREAD

**Issue by jminor** [markreidvfx/pyaaf2#49]
We've seen a few instances of corrupt-looking strings in some string values.

In the example AAF file linked on this OTIO issue: https://github.com/PixarAnimationStudios/OpenTimelineIO/issues/474 we get this value for AvidASPIPlugInName:

`Time Compression Expansion\u0000\u0000\uf37e\u1029`

but aafDump shows:

`Time Compression Expansion`

**Comment by markreidvfx** [comment]
Should be fixed in the 37de8c10d3c3495cc00c705eb6c5048bc4a7e51f

**Comment by jminor** [comment]
I verified that your fix works for our test case. Thanks @markreidvfx !
