### ISSUE TITLE
Information on external mxf linking and metadata

### ISSUE THREAD

**Issue by johneast** [markreidvfx/pyaaf2#50]
Hi

First of all, thanks for this library. For the project I'm working on the server is not able to use the AMT SDK (OS type) so having a pure python version is incredibly useful.

My use case is that on a server I'm going to build the files that need delivering to a workstation (aaf and associated external dnxhd mxf files). I've done some preliminary tests with linking external mxfs and that seemed to work. However, where we build the aaf file, and where the files get consumed are two different locations so that paths to the mxf files will be very different for the user vs what is on the server. My understanding is that the aaf file will contain to the path to the mxf when it was created so this aaf file won't be able to work with MC. Is this correct?

Admittedly my understanding of the AAF format is *very* limited so my understanding maybe completely off.

What I'd like to do is create an aaf file that contains references to mxf files _as they appear to the end user_.

Also, I'd like to include locator information in the aaf file. Is this possible? Are there any examples?

**Comment by markreidvfx** [comment]
If your using opatom MXF, Avid MC doesn't need the locator's URLString at all, it uses the MobIDs inside the MXF to link.   If they match Mobids in the aaf file and the mxf file is in one of its media file folders.

If you doing AMA linking I believe you can have multiple network locators but I haven't tested.  
Avid also sometimes adds a "UNC path" user comment to master mobs that only show up in the bin, does nothing but it is user facing.

**Comment by johneast** [comment]
Thanks for the response.

I will look into this.
