### ISSUE TITLE
Add metadata to custom columns and leave tape name blank?

### ISSUE THREAD

**Issue by kevinparkbss** [markreidvfx/pyaaf2#51]
Hi Mark!

I have two related questions regarding metadata. 

First question is regarding the ability to write metadata to custom fields for the Avid. Is there an ability to write metadata to a custom column that can be chosen via the bin menu inside the Avid? If so, would you be able to point me in the right direction to implement that?

Second, is it possible to leave the tape name field empty when creating an embedded sequence aaf? If I leave it null it defaults to the sequence_name.#.

Thanks!

**Comment by markreidvfx** [comment]
sorry for the late reply, any TaggedValue that is added to a MasterMob['UserComments'] will show in MC bins. TaggedValue.name will be the column and its value will be the value.

I'm not sure how your creating you Mobs, but the tape name is the Name of the SourceMob in the chain that has a TapeDescriptor on it. If you change its Mob.name it will change the tape name.

**Comment by kevinparkbss** [comment]
Thanks mark! the TaggedValue works great. One follow up question though. I want to be able to set the color column of a clip, meaning the color box that shows up next to the name and in the timeline in Avid. I believe that this is a TaggedValue as well but in the MobAttributesList as opposed to user comments. When I open an aaf with colored clips in the tree model, I see that _COLOR_R, _COLOR_G, and _COLOR_B values are set. Do you know how I can set these values in pyaaf when creating an aaf?

**Comment by markreidvfx** [comment]
you should be able to do the same way as the UserComments

```python
tag = f.create.TaggedValue("_COLOR_R",  49664) #think this is 16bit color value
mob['MobAttributeList'].append(tag)
```

**Comment by kevinparkbss** [comment]
Thanks Mark! I don't know why but when I had tried that initially, it didn't work but I just tried it again and it works great! I think perhaps I didn't have valid RGB values. Or maybe I was testing by giving just one of the values. In any case, it works and it's like magic :)
