### ISSUE TITLE
Question - AAF version

### ISSUE THREAD

**Issue by ilansr** [markreidvfx/pyaaf2#6]
Can you please tell me what AAF format version does this library comply with?
Also, would it generate Legacy objects similarly to pyaaf1?

Thanks and keep up the awesome work!!

**Comment by markreidvfx** [comment]
The AAF's generated should be compatible with AAF Object Specification v1.1.
But I also include a lot of Avid Extensions by default, as its my main use case. 
The default classes is defined here:
https://github.com/markreidvfx/pyaaf2/blob/master/aaf2/model/classdefs.py

What legacy objects are you looking to generate?

**Comment by ilansr** [comment]
At the moment, i am using pyaaf1 to add new timecodes.
These are creates as legacy. I would much prefer them as non-legacy objects. Would pyaaf2 be a good alternative for me?

**Comment by markreidvfx** [comment]
Yes you can create timecode components with/without legacy datadefinitions
https://github.com/markreidvfx/pyaaf2/blob/master/aaf2/model/datadefs.py#L110

**Comment by ilansr** [comment]
This is great.
Are there any migration guidelines when moving from aaf1 to aaf2 or is the api identical?

**Comment by markreidvfx** [comment]
I don't have a porting guide, but you can check the doscs and tests. It's not 100% backwards compatible with pyaaf1, but the API is very similar.

**Comment by ilansr** [comment]
Will do.
Thanks!
