### ISSUE TITLE
Create Offline Clip to relink in Avid

### ISSUE THREAD

**Issue by kevinparkbss** [markreidvfx/pyaaf2#61]
Hi Mark! Thanks so much for your help so far. One more big thing I'd like to accomplish is to create clips in a sequence aaf that imports as offline clips in the Avid. The idea is that I can mix and match clips on a sequence that have embedded media, as well as some that are offline clips, so that I can relink these offline clips to already imported media in the Avid, i.e. new clips vs old.

I have a feeling that basically it's the same process as creating embedded media clips but instead of importing dnxhd essence into the sourcemob, I need to create CDCI descriptors for the sourcemob. I've been able to create a sequence with offline clips but it imports into the avid with an error (CM_LABEL_NOT_UNIQUE) and the offline clips don't have tape names or timecodes so I can't relink them to the previously imported clips. 

Would you be able to point me to an example of how I can specify a clip to have all the attributes of a dnxhd 36 master clip but just not have any actual media embedded? Thanks!

**Comment by haraldjordan78** [comment]
Is it possible that you just want to mimic what link_external_mxf does?

The mxf metadata is being taken from the MXFFile class which takes all the needed metadata from, you probably can take the data from an existing template mxf file and change the needed few pieces like duration etc...

**Comment by kevinparkbss** [comment]
Thanks for the tip Harald! You're right in that all the necessary metadata is in there. I've only used it for single shot aaf's. I'll have to see how to integrate it into a sequence aaf that I build shot by shot.
