### ISSUE TITLE
Cannot import_rawvideo_essence with mp4. Pixel layout not encoding

### ISSUE THREAD

**Issue by atomicfruitcake** [markreidvfx/pyaaf2#62]
I am trying to the the `SourceMob` method `import_rawvideo_essence`. After some debugging I think the issue may be due to `pixel_layout` parameter data type being incorrect. I've tried many different types and cannot get it to work.

Assuming the 'sample.mp4` is in the same directory, the following code can reproduce the issue.

```python
import aaf2

with aaf2.open("example2.aaf", 'w') as f:

    # objects are create with a factory
    # on the AAFFile Object
    mob = f.create.MasterMob("Demo2")

    # add the mob to the file
    f.content.mobs.append(mob)

    edit_rate = 25

    tape_mob = f.create.SourceMob()
    tape_mob.import_rawvideo_essence(
        path="sample.mp4",
        edit_rate=edit_rate,
        width=480,
        height=360,
        pixel_layout=(4, 3),
    )
```

From my debugging attempts, the error is coming from `aaf2/types.py:682` when attempting to encode the `pixel_layout` argument here:
```python
value = typedef.encode(data[key])
```

From the above snippet, the `data` object is an integer of value 4, therefore the error shows the following:
```
File "/usr/local/lib/python3.7/site-packages/aaf2/mobs.py", line 247, in import_rawvideo_essence
    descriptor['PixelLayout'].value = pixel_layout
  File "/usr/local/lib/python3.7/site-packages/aaf2/properties.py", line 55, in func_wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aaf2/properties.py", line 162, in value
    self.data = self.typedef.encode(value)
  File "/usr/local/lib/python3.7/site-packages/aaf2/types.py", line 354, in encode
    result += element_typedef.encode(item)
  File "/usr/local/lib/python3.7/site-packages/aaf2/types.py", line 680, in encode
    value = typedef.encode(data[key])
TypeError: 'int' object is not subscriptable
```

What do I need to provide for `pixel_layout` to import the mp4 as an essence?

**Comment by markreidvfx** [comment]
`import_rawvideo_essence` is for embedding raw uncompressed video, the footage your trying to use looks like its in a MP4 container.

**Comment by atomicfruitcake** [comment]
Thanks @markreidvfx . Would you recommend using a .mxf file instead?

**Comment by markreidvfx** [comment]
Depends on what your trying to do and for what Application. If you want to embed it, take a look the `import_media.py` example. It trys to convert the media via ffmpeg to a embeddable format.
linking externally to a mxf or supported ama format is possible but can be tricky to get an Application to accept.  These methods [here](https://github.com/markreidvfx/pyaaf2/blob/master/aaf2/content.py#L71) try to do that, but still rough to use and your mileage may vary...

**Comment by atomicfruitcake** [comment]
That's great @markreidvfx, will give this a whirl.
