### ISSUE TITLE
Create AAF with references to mxf op atom to use with avid interplay

### ISSUE THREAD

**Issue by NKnuelle** [markreidvfx/pyaaf2#64]
Hi,

I use pyaaf2 to create an aaf file which links to OP Atom MXF files. I use this AAF file to checkin new media files to Avid Interplay. The code looks like this:
```
from pathlib import Path
import aaf2

data_folder = Path('//example/workspace/Avid MediaFiles/MXF/folder/')

first_mxf = data_folder / '1315LY_v1.mxf'
second_mxf = data_folder / '1315LY_a1.mxf'
third_mxf = data_folder / '1315LY_a2.mxf'
forth_mxf = data_folder / '1315LY_a3.mxf'
fifth_mxf = data_folder / '1315LY_a4.mxf'

out_file = "test2.aaf"
with aaf2.open(out_file, 'w') as f:
    f.content.link_external_mxf(first_mxf)
    f.content.link_external_mxf(second_mxf)
    f.content.link_external_mxf(third_mxf)
    f.content.link_external_mxf(forth_mxf)
    f.content.link_external_mxf(fifth_mxf)
```
This is just sample code for simple testing.
The AAF is generating all fine.

I use the Interplay Web Services API from Avid to check this AAF file into interplay. This is working without errors. I am also able to get this asset from Interplay Access into Avid Media Composer. Video and Audio is online.

There is only 1 problem:
Interplay Access shows some metadata like "media size" and "file locations". The "file locations" show all referenced media files (so all OP Atom files).

The checked-in AAF from pyaaf generates a masterclip which is shown in Interplay Access. But masterclip has media size 0 and no file locations. The problem now is, that I can't delete the referenced media files within Interplay Access, because it does not "see" the referenced MXF files.

All Masterclips which are generated by other programs (commercial transcoders, Avid MC,..) have those properties set..

Does anybode know why this happens or has some ideas about this?

I know this is a very specific question but maybe I am doing something wrong with linking the mxf's using pyaaf2?

Thanks for any hints!

**Comment by markreidvfx** [comment]
It sounds like the pyaaf2 mxf parser needs to add some more metadata to the aaf. I unfortunately do not have access to interplay. But the best way to debug issues like this is to compare a AAF that works against one the pyaaf2 generates. Are you able to share a sample AAF and MFX?

**Comment by NKnuelle** [comment]
Hi,
I am not sure how to get a valid sample AAF, because every other commercial software we use seems to generate these AAF files under the hood. I don't know how to get these so I can't provide any samples. I am going to create some AAF files via Avid and check if those files are working. Maybe I can post some samples then. Is there any method within pyaaf2 to read the AAF and post all content in a human readable format?

**Comment by NKnuelle** [comment]
Hello again,
I got some AAF samples. For better comparison I generated one AAF file via pyaaf2 and one with Avid MC from the same mxf op1a sources. The Avid MC AAF is working fine in Avid Interplay, the pyaaf2 generated one produces the issues mentioned above.
[Avid AAF](https://www.file-upload.net/download-13682155/132078.aaf.html)
[pyaaf2 AAF](https://www.file-upload.net/download-13682156/test2.aaf.html)

**Comment by NKnuelle** [comment]
Any update on this topic?
I compared both AAF's and mentioned that the order of mob's, sourceclip and masterclip is different. I iterated over all mob's in the AAF and printed their names. The print order was then different between both AAF's. But I am not sure if this is related to the problem.

It seems to be a bit complicated to filter the output of AAF dumps. I am still searching for a function to filter metadata etc. to easier compare the AAF files.

**Comment by markreidvfx** [comment]
Still haven't had much time to look into this, but the order of the mobs shouldn't matter.

**Comment by NKnuelle** [comment]
@markreidvfx 

I managed to find out that the problem maybe relates to missing network locators inside the AAF. Maybe there is something wrong with linking external MXF's on a network drive? Is the library testing against this case?

**Comment by NKnuelle** [comment]
I uploaded two sample AAFs with their dot representation. The dot files can be viewed via Graphwiz or similar programs.

There are major differences in what data is stored in the AAF. I think the biggest problem here is that Avid attaches a NetworkLocator to every Source Clip. PyAAF2's link_external_mxf-function does not seem to do that.

This is the textual representation of the .dot file from Avid AAF:

> N69 [ width = 4.03,  label = "{TimelineMobSlot\n.  | SlotID = 1\n | SlotName = A1\n | PhysicalTrackNumber = 369164801\n | EditRate = 25/1\n | Origin = 0\n}"];
N70 [ width = 3.25,  label = "{Sequence\n.  | DataDefinition = -\>Sound\n | Length = 868\n}"];
N71 [ width = 5.2,  label = "{SourceClip\n.  | DataDefinition = -\>Sound\n | Length = 868\n | SourceID = 060a2b340101010101010f0013000\n000-5d414588-5bd5-3c0a-060e2b347f7f2a80\n | SourceMobSlotID = 5\n | StartTime = 15146\n}"];
N72 [ width = 5.2,  label = "{PCMDescriptor\n.  | SampleRate = 48000/1\n | Length = 1666560\n | ContainerFormat = -\>MXF\n | QuantizationBits = 24\n | Locked = False\n | AudioSamplingRate = 48000/1\n | AudioRefLevel = -20\n | ElectroSpatial = ElectroSpatialFormulati\non_SingleChannelMode\n | Channels = 1\n | AverageBPS = 144000\n | BlockAlign = 3\n | SequenceOffset = 0\n | DialNorm = 27\n | DataOffset = 266240\n}"];
N73 [ width = 5.46,  label = **"{NetworkLocator\n.  | URLString = file://ks-sysdir-hr/ks-inges\nt/avid%20mediafiles/mxf/ks-ffastrans/1320\n78_a4.mxf\n}"];**

This is the .dot file from pyaaf2 AAF:

> N7 [ width = 2.99,  label = "{TimelineMobSlot\n.  | SlotID = 2\n | SlotName = A1\n | PhysicalTrackNumber = 1\n | EditRate = 48000/1\n | Origin = 0\n}"];
N8 [ width = 4.29,  label = "{Sequence\n.  | DataDefinition = -\>DataDef_Sound\n | Length = 4364160\n}"];
N9 [ width = 5.2,  label = "{SourceClip\n.  | DataDefinition = -\>DataDef_Sound\n | Length = 4364160\n | SourceID = 060a2b340101010101010f0013000\n000-5d414992-266f-3c1a-060e2b347f7f2a80\n | SourceMobSlotID = 1\n | StartTime = 0\n}"];

You can see that both PCMDescriptor and NetworkLocator are missing here.

Do you know how to change this behaviour?

**Comment by NKnuelle** [comment]
Update: I tried using the method create_ama_link which gives me a different AAF with a NetworkLocator. But this NetworkLocator has a different file path. This path is also escaped differently from the Avid produced AAF:

`N64 [ width = 4.03,  label = "{TimelineMobSlot\n.  | SlotID = 1\n | SlotName = V1\n | PhysicalTrackNumber = 352388609\n | EditRate = 25/1\n | Origin = 0\n}"];
N65 [ width = 4.55,  label = "{Sequence\n.  | DataDefinition = -\>DataDef_Picture\n | Length = 2273\n}"];
N66 [ width = 5.2,  label = "{SourceClip\n.  | DataDefinition = -\>DataDef_Picture\n | Length = 2273\n | SourceID = 060a2b340101010101010f0013000\n000-5d414992-265f-3c1a-060e2b347f7f2a80\n | SourceMobSlotID = 1\n | StartTime = 4534\n}"];
N67 [ width = 5.2,  label = "{CDCIDescriptor\n.  | SampleRate = 25/1\n | Length = 2273\n | ContainerFormat = -\>ContainerDef_AAFKLV\n | Compression = 04010202-0132-3102-060e2b3\n40401010a\n | StoredHeight = 540\n | StoredWidth = 1920\n | SampledHeight = 540\n | SampledWidth = 1920\n | FrameLayout = SeparateFields\n | VideoLineMap = 21 584\n | ImageAspectRatio = 16/9\n | ComponentWidth = 10\n | HorizontalSubsampling = 2\n | VerticalSubsampling = 1\n | MediaContainerGUID = 60eb8921-2a02-4406-\n891cd9b6a6ae0645\n | ResolutionID = 3416\n | FrameSampleSize = 568832\n}"];
N68 [ width = 5.46,  label = "{NetworkLocator\n.  | URLString = file://\\\\ks-sysdir-hr\\ks-\ningest\\Avid MediaFiles\\MXF\\KS-FFASTRAN\nS\\nina-schmidt_www-Stimme-Professor-K1-X\nQD-15~\n}"];
N69 [ width = 5.2,  label = "{SourceMob\n.  | MobID = 060a2b340101010101010f0013000000\n-5d414992-266f-3c1a-060e2b347f7f2a80\n | Name = Mob\n | LastModified = 2019-07-31 07:56:02.00\n | CreationTime = 2019-07-31 07:56:02.00\n}"];`

**Comment by NKnuelle** [comment]
Hey again,

I managed to find the issue and I was able to make some changes which lead to a working AAF for Avid Interplay usage. For this I made a fork of this library. I modified the link_external_mxf method and sub-methods so that NetworkLocators are written to the AAF file. With this AAF Interplay recognizes all assets and marks them as "native essence" instead of "AMA".

Greetings
Nils

**Comment by markreidvfx** [comment]
Glad to hear you got it working! I took a quick look at your fork and its seems like a simple change, If you'd like to to get the feature added to my branch feel free to create a pull request, I'd gladly merge it!

**Comment by TrevorAyl** [comment]
Interesting. Did this ever get merged?

**Comment by Robinsper** [comment]
I'm having a similar issue and as Trevor I would also like to know if this was merged.
My issue is that the files in Interplay show an offline status, however, I can play the clip in the monitor and reveal the source in Nexis when I drag it to a bin. The issue with the offline status is causing other oddities on the clip.
I can post snippets of my code but since there has been no response in 7 months, I'm not sure if anyone is following these issues anymore.
