### ISSUE TITLE
How to read Start time and length from the nested source clip on a audio track

### ISSUE THREAD

**Issue by sanfx** [markreidvfx/pyaaf2#69]
from source_clip.data.media_kind I get to know its a Sound, and I now want to get the StartTime 
so I do source_clip["StartTime"] it gives me 0 but if I open the same in otioview I can see the start time in frames format .Any help will be greatly appreciated.

**Comment by markreidvfx** [comment]
sourceclips reference tracks and start times into other mobs, which then references tracks and start times in other mobs forming a chain. You need to follow this chain until you hit the bottom sourceclip that reference nothing. In a nutshell adding all the StartTimes in this chain together calculates the master start time.

**Comment by sanfx** [comment]
yea I did got and updated in the editorial query (now archived) it but I later forgot to update here as I was leaving later in 2 months. But thanks for replying back here. Its less than 3.
