### ISSUE TITLE
Performance issue linking external wavs

### ISSUE THREAD

**Issue by muchbatter** [markreidvfx/pyaaf2#72]
I'm using pyaaf2 to create AAF files that can contain as many as about 5k-10k short clips, using `aaf.content.link_external_wav(metadata)`. This seems to be causing pyaaf2 some trouble. It can take as much as 30 minutes for my computer to link them all. I ran a performance test using gprof2dot which gives a visualization of where the processing time is being spent.

![perf-pyaaf2](https://user-images.githubusercontent.com/58020669/69307019-68205b00-0bf7-11ea-9b3d-2653bef7b3bc.png)

It seems that linking 5k wav files is leading to 15k calls to `aaf2.properties.extend` (for each of the 3 mobs), and I think that creating a tree this large is causing a problem.

Do you have any suggestions for how this could be optimized?

**Comment by markreidvfx** [comment]
Interesting, looks like most of the time is spent in the lower CompoundFileBinary layer. Cfb is basically a fat32 filesystem, what ends up happening when you create many Mobs is they get thrown in the same directory and it gets progressively slower to add more. Unfortunately I don't have a good solution off the top of my head to speed up dirEntry insert. 

Something that might speed this case up a little is to add a cache the utf16 decode of DirEntry.name.

**Comment by NKnuelle** [comment]
I am not sure if threading would be an alternative here? But maybe this will lead to more performance issues, because it seems like it is a low-level api function..

**Comment by markreidvfx** [comment]
If you don't need all the mobs in the same AAF you could also generate multiple in parallel using a process pool.

**Comment by muchbatter** [comment]
Unfortunately the clips all need to go into the same AAF. Caching the name seems like it may be the right place to start. I'm not a particularly experienced programmer but I did find this python library for cfb access, maybe it could be a helpful reference here? https://github.com/decalage2/olefile

**Comment by iluvcapra** [comment]
How many tracks/slots do you need? Maybe you can make an AAF per track?

**Comment by muchbatter** [comment]
I could, but is there a way to then easily merge them other than one at a time? If not, then I think taking that approach would cause as much of a headache as it solves. I’m working with pro tools

**Comment by markreidvfx** [comment]
Here a simple script that replicates the issue

```python
import sys
import time
import io

from aaf2.cfb import CompoundFileBinary

import cProfile, pstats, StringIO
pr = cProfile.Profile()
pr.enable()
try:
    with io.open("out.aaf", 'wb+') as f:
        c = CompoundFileBinary(f, 'wb+')
        global_start = time.time()
        for i in range(3000):
            start = time.time()
            c.root.touch("%010X" % i)
            if i % 25 == 0:
                print i, time.time() - start

        print "completed in ", time.time() - global_start
except:
    raise

finally:
    pr.disable()
    s = StringIO.StringIO()
    sortby = 'cumulative'
    # sortby = 'tottime'
    ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
    ps.print_stats()
    print s.getvalue()
```

**Comment by markreidvfx** [comment]
Caching the DirEntry names does help, I pushed the change  in e1b7313a739bcbe9fc1a6a9538de8cd8590e4159. 
The problem still exists but the performance should be better a lot better now.

**Comment by markreidvfx** [comment]
In-order insert is pretty much the worst case for building a binary tree. The only way to really make this problem go away is to implement rbtrees or some other self balancing tree algorithm. Or preferably figure out some way to delay the building of tree to a later time.

I added this method for now `f.content.dir.rebalance_children_tree()` if you run it every like 512->2048 calls to  `aaf.content.link_external_wav(metadata)` it should keep the tree balanced and the inserts won't take forever, but when you start getting up to 100,000 mobs rebalancing ends up being the bottleneck.

**Comment by markreidvfx** [comment]
It wasn't fun but red-black trees have now been implement! Adding and removing child DirEntry's should now scale near O(log n) instead of linearly. Hopefully this resolves your issue.

**Comment by muchbatter** [comment]
This is awesome! I'm so excited to try it out. I'll drop an update once I get to it!!
