### ISSUE TITLE
Error when doing aaf2.Open to retrieve a stream from an aaf coming from Windows

### ISSUE THREAD

**Issue by lacroixthomas** [markreidvfx/pyaaf2#75]
I have an aaf generated from Windows with Avid, I have an error after doing:
`with aaf2.Open(filepath, 'rb') as f:`

I needed to revert this change to be able to stop having the error `array index out of range `
 https://github.com/markreidvfx/pyaaf2/blob/master/aaf2/cfb.py#L1158 

I've seen that the error `array index out of range` is coming from: 
https://github.com/markreidvfx/pyaaf2/blob/master/aaf2/cfb.py#L1519

When you say `some files write zero difat instead of FREESECT`, is it for aaf generated with pyaaf2 or Avid ? 

Using Avid 2019.7 with Windows 10 Pro

**Comment by markreidvfx** [comment]
Are you able to share a AAF that has this issue? I will try and figure out why the fix was added.

**Comment by lacroixthomas** [comment]
[20Jan_000_v001.aaf.zip](https://github.com/markreidvfx/pyaaf2/files/4092552/20Jan_000_v001.aaf.zip)

Awesome thank you

**Comment by markreidvfx** [comment]
Okay I reverted the change. Thanks for reporting the issue! Would I be able to add this AAF file to the project for a unit test, so this doesn't break in the future?
