### ISSUE TITLE
Timecode FPS Value Truncation?

### ISSUE THREAD

**Issue by zconnolly** [markreidvfx/pyaaf2#76]
Hello, I am looking into providing a better code snippet example, but I thought I would ask here to see if this is a misunderstanding on my part.

> $tape_mob.root.create.Timecode(23.98)

When instantiating [the Timecode object](https://pyaaf.readthedocs.io/en/latest/api/aaf2.components.html#aaf2.components.Timecode) with a float fps like 23.98, I find that retrieving the value (_tc.properties()_) shows that it is truncated or casted to an int so we end up with 23.  This also seems to be the case when using the self.fps setter. This then leads to a TC start miscalculation value in avid.

Is the Timecode fps value special in some way that requires it to always be an int, or is this an actual issue?

Thanks in advance!

**Comment by markreidvfx** [comment]
`FPS` on a Timecode object is a `UInt16` according to the spec, 
![image](https://user-images.githubusercontent.com/814966/75490780-a8ffdc80-5969-11ea-93a2-b45148b7649d.png)

23.98 fps is not a standard timecode as far as I know, the correct behaviour I think is to round up the frame rate. I'm not sure off the top of my head if its also required to scale the start position too. for example example:  frame 100/23.98 = x/24

**Comment by zconnolly** [comment]
Thanks much for getting back so quickly.  Agreed that the spec isn't all that straightforward there.

It does give the hints "videotape or audio tape"... I'm wondering if that restriction is a requirement of purely physical media/film where you couldn't account for partial frames with film timecode.

The spec also has a bit of seemingly related details in the pulldown section:
> Since NTSC videotape has a speed of 29.97 fps, in order to get an exact ratio of 4 to 5, the film is played at 23.976 fps in the telecine machine instead of **its natural speed of 24 fps.**
> A tape Metadata Object describing a tape produced by telecine should have edit rates of 30 fps for its tracks. Although the **videotape is always played at 29.97 fps, the content has a speed of 30 fps.**

From [this post](https://blog.frame.io/2017/07/17/timecode-and-frame-rates/) I see other few hints:
> But timecode can only count in whole rather than fractional frames.
> Many older sound recorders only have real-time timecode clocks or can only do 24fps timecode. 

So I'd guess we'd round up to the closest available integer frame rate as a good educated guess moving forward.

I don't think you'd have to scale the start frame because you could run into the same issue with a fraction of a frame or perhaps that's when you have to set the `drop` property.

**Comment by zconnolly** [comment]
And for reference, I am coincidentally just noticing AVID TC metadata column options available are: 24,25,25PD,30, and 30NP.
