### ISSUE TITLE
CMB errors with Premiere AAF exports

### ISSUE THREAD

**Issue by iluvcapra** [markreidvfx/pyaaf2#77]
I've gotten this message with a few AAFs now:

> WARNING:root:fat sector count missmatch difat: 3792 header: 3685

This usually doesn't cause any problems. Something else Premiere seems to like doing is to set ALL the CompositionMobs in the file to `Usage_TopLevel` so I've been using pyaaf2 to fix this.

However I've run into an AAF from Premiere that gives me the sector count warning, and when I try to edit the file the result is always corrupt, I get:

> WARNING:root:mini stream size missmatch: 1094912 != 1048576, using size from minifat

I'm sorry I can't attach the AAF in question as it's under an NDA, but what could be going wrong and is there a workaround?

**Comment by markreidvfx** [comment]
without a sample, not sure how to resolve this issue, will close it for now
