### ISSUE TITLE
AAF files with embedding footage not working on Avid Media Composer 6.5.4 nor 8.5.3

### ISSUE THREAD

**Issue by hasielhassan** [markreidvfx/pyaaf2#8]
Hi i'm just starting playing with this and everything seems pretty exiting!
Thanks for this effort!

Sadly my Avid is complaining with the resulted aaf files, even with the example from the docs:
http://pyaaf.readthedocs.io/en/latest/#embedding-footage-example

Those are my first steps so its most surely that i'm missing some technical details either in the transcoding or the structure of the aaf.

Following the example exactly produce an aaf file that loads the clips in the avid, but not the media, logging this error in the console:
```
Clip (internal): Demo2.PHYS
    Minor Change: Error with media reference (clip will be offline).

Error importing media for 'Demo2'. (FileMob 1 of 2, VIDEO) Error: 'DIDReader::XraiseUnexpectedStreamStatus async file system error.'
Error importing media for 'Demo2'. Error: 'CM_INCOMPAT_TRACK_TYPES' 
```

I'm attaching the aaf file.
[example2.zip](https://github.com/markreidvfx/pyaaf2/files/1820597/example2.zip)

**Comment by markreidvfx** [comment]
Sorry for the delay. Your AAF works for me in MC 2018.1. Do those version of MC not support the DNxHR codec? Can you try with DNxHD footage? here is a command to generate some
```
 ffmpeg -f lavfi -i testsrc=size=1920x1080 -frames:v 24 -vcodec dnxhd -pix_fmt yuv422p -vb 36M sample.dnxhd
```

**Comment by hasielhassan** [comment]
That one did the trick, i didn't read any incompatibility from AVID but is good to know.
Thanks so much!
