### ISSUE TITLE
Not yet understanding the time code output

### ISSUE THREAD

**Issue by communque** [markreidvfx/pyaaf2#80]
Trying to learn pyaaf2.  It may be my lack of familiarity with python -- I generally work in JS.
Testing the code sample at https://github.com/markreidvfx/pyaaf2/issues/14#issuecomment-457799777 on a [sample AAF](https://github.com/markreidvfx/pyaaf2/files/4660181/AafTest.aaf.zip) with only 4 clips and getting the following output:

```
864.mp4
walking SourceClip 170556
walking SourceClip 0
   []
862.mp4
walking SourceClip 169836
walking SourceClip 0
   []
861.mp4
walking SourceClip 163764
walking SourceClip 0
   []
863.mp4
walking SourceClip 170088
walking SourceClip 0
   []
```

The code example suggests suggests in should be converting to something along the lines of an hh:mm:ss:ff.
But as they are I'm not immediately recognizing what multiple of frames, secs or ticks output might be representing.

Here's an actual listing of edits in the sample AAF, EDL-ish style, and more or less what I'm trying to achieve with pyaaf2

Track Type|Track Layer|Clip Name|Master TC Start|Master TC End|Source TC Start|Source Tc End|Duration
----------|-----------|---------|---------------|-------------|---------------|-------------|--------
VIDEO|1|861.mp4|00:00:00:00|00:00:08:12|00:03:56:08|00:04:04:20|00:00:08:12
VIDEO|1|862.mp4|00:00:08:12|00:00:13:06|00:00:02:21|00:00:07:15|00:00:04:18
VIDEO|1|863.mp4|00:00:13:06|00:00:21:13|00:00:02:18|00:00:11:00|00:00:08:06
VIDEO|1|864.mp4|00:00:21:13|00:00:53:02|00:00:06:02|00:00:37:16|00:00:31:14
AUDIO|1|861.mp4|00:00:00:00|00:00:08:12|00:03:56:08|00:04:04:20|00:00:08:12
AUDIO|1|862.mp4|00:00:08:12|00:00:13:06|00:00:02:21|00:00:07:15|00:00:04:18
AUDIO|1|863.mp4|00:00:13:06|00:00:21:13|00:00:02:18|00:00:11:00|00:00:08:06
AUDIO|1|864.mp4|00:00:21:13|00:00:53:02|00:00:06:02|00:00:37:16|00:00:31:14

**Comment by Md-Akdas** [comment]
I've similar requirements to get the timeline.
have you found the solution ?

**Comment by communque** [comment]
Unfortunately, no.  LMK if you get any leads toward a solution.

**Comment by Md-Akdas** [comment]
Do you know any other library (any language) or tool to extract info from AAF file?

**Comment by communque** [comment]
Not immediately.  Your post got me back to reviewing progress notes.  I have a few leads, one which never got back to me, and a link which, now that I've revisited it, has devolved into a foreign language porn site.  I'll follow up with the former, ignore the latter (I suspect AAFs is not their thing anymore)

**Comment by markreidvfx** [comment]
AAF uses what is calls `edit units` to express time durations. How long a edit unit is determined by the `edit rate`  of whatever timeline the clip/component is in.  If you multiply the edit unit by the edit rate you will get a the time in seconds.

edit rate = 1/30
edit unit = 100

100 * 1/30 =  3.333..  seconds

here is what the aaf spec says
```
A component in a TimelineMobSlot has a duration expressed in edit
units. The relation between edit units and clock time is determined by the edit rate of the
TimelineMobSlot that has the component
```

clip in a timeline has a start and length in edit units. To find the position of a clip in timeline you add up all the lengths of the components that preceded it.

Source TC is a little more involved, and I think I've answered this question before in another issue.
Anyway, you walk the clip reference chain, using the clips mob_id and slot_id untill you reach the the bottom of the hierarchy, a clip the references a NULL mob_id. The Mob this clip is part of normally has a TapeDescriptor or ImportDescriptor on it.  If you add the start times of all the clips it took to get there, you get the Source TC.  The bottom Mob also normally has a timecode track on it that you can use to express the Source TC in the correct frame rate.

**Comment by communque** [comment]
@markreidvfx Thanks for the response.  Will revisit all this as soon as I have a moment free.
