### ISSUE TITLE
Tape name or Source File from subclip with start and end frame?

### ISSUE THREAD

**Issue by kevinparkbss** [markreidvfx/pyaaf2#84]
Hi Mark!

I was just curious if subclips, specifically audio subclips reference the Tape Name or Source File anywhere? I see that subclips are composition mobs in the AAF and I can get the subclip name, but what I'd really like to do is get the tape name, source file, or master clip name that it was subclipped from, and the relative start and end frame from that source material.

Thanks in advance!

**Comment by markreidvfx** [comment]
Sorry for the late reply. Yes, avid seems use composition mobs for sub clips. To find their tape name shouldn't be any different though, you follow the reference chain down till you find a mob with a null mob_id and a tape descriptor. For start TC you add all the start times together and the timecode track you find on the tape mob.
