### ISSUE TITLE
audio track ordering with content.mobs.append

### ISSUE THREAD

**Issue by benhackbarth** [markreidvfx/pyaaf2#85]
Hello! I am trying to integrate aaf2 into a project (https://github.com/benhackbarth/audioguide) for working with audio concatenation in DAWs. I've run into a small issue: I cannot seem to get tracks to appear in the proper order in a DAW (in my case Logic; I have not tested this with pro tools). Each time I write the file, track orders are shuffled (seemingly randomly) - e.g. tracks appear in the order "Track5", "Track4", "Track8", "Track6", etc, in Logic. Minimal code below. Perhaps I am misunderstanding something about file.content.mobs.append()?

Thanks for this great project!

```
import os, aaf2

f = aaf2.open('/Users/ben/Desktop/test.aaf', "w")
aaf_sr = 44100

my_sf_meta = {'streams': [{'index': 0, 'codec_type': 'audio', 'sample_rate': '44100', 'channels': 1, 'duration_ts': 502892}], 'format': {'filename': '/Users/ben/Documents/audioguide/examples/cage.aiff', 'format_name': 'aiff'}}

master_mob, source_mob, tape_mob = f.content.link_external_wav(my_sf_meta)

for i in range(10):
	sequence = f.create.Sequence(media_kind="sound")
	sequence.components.append(f.create.Filler("sound", int(aaf_sr*0.5))) # silence
	sequence.components.append(master_mob.create_source_clip(slot_id=1, start=0, length=int(aaf_sr*0.5))) # sound
	comp_mob = f.create.CompositionMob("Track%i"%i)
	f.content.mobs.append(comp_mob)
	timeline_slot = comp_mob.create_timeline_slot("%i" % aaf_sr)
	timeline_slot.name = "Track%i"%i
	timeline_slot.segment = sequence	

f.close()
```

**Comment by markreidvfx** [comment]
I think this should accomplish  what your trying to do. Only creating one CompositionMob.

```python
import os, aaf2

f = aaf2.open('/Users/ben/Desktop/test.aaf', "w")
aaf_sr = 44100

my_sf_meta = {'streams': [{'index': 0, 'codec_type': 'audio', 'sample_rate': '44100', 'channels': 1, 'duration_ts': 502892}], 'format': {'filename': '/Users/ben/Documents/audioguide/examples/cage.aiff', 'format_name': 'aiff'}}

master_mob, source_mob, tape_mob = f.content.link_external_wav(my_sf_meta)
comp_mob = f.create.CompositionMob()
f.content.mobs.append(comp_mob)

for i in range(10):
	sequence = f.create.Sequence(media_kind="sound")
	sequence.components.append(f.create.Filler("sound", int(aaf_sr*0.5))) # silence
	sequence.components.append(master_mob.create_source_clip(slot_id=1, start=0, length=int(aaf_sr*0.5))) # sound
	
	timeline_slot = comp_mob.create_timeline_slot("%i" % aaf_sr)
	timeline_slot.name = "Track%i"%i
	timeline_slot.segment = sequence	

f.close()
```

**Comment by benhackbarth** [comment]
Thank you Mark. I confirm that this now works as expected. Cheers.

One other small question if you do not mind. My understanding from looking at the source is that it isn't possible to create audio fadeins/fadeouts with pyaaf2. If there is a way of doing this, I would appreciate knowing how!

Thanks, Ben

**Comment by markreidvfx** [comment]
I haven't tried doing audio fades with pyaaf2 before, but it should be possible. There are no helper functions to do it.  The best place to begin would be with a sample AAF of what you're trying to replicate, then study it's structure.

**Comment by benhackbarth** [comment]
Got it, will take a look when I get a chance. thanks again.
