### ISSUE TITLE
How tolerant of badly structured AAFs is this library?

### ISSUE THREAD

**Issue by mrlimbic** [markreidvfx/pyaaf2#86]
I've been investigating using AMWA's official java library for reading/writing AAFs (Maj). However it is hyper strict with validation and has no "tolerant" mode. So many AAFs created by common apps fail because they do something silly when creating the AAF.

A typical blowup today from an avid media composer AAF was this "Cannot create a new extendible enumeration property value from the given AUID identity as it does not match the identity of an enumeration element of type TransferCharacteristicType."

How does the pyaaf2 library deal with invalid data constructs? I am getting frustrated and thinking of switching to pyaaf2. I'd prefer just a warning and ignore any badly constructed data.

**Comment by markreidvfx** [comment]
pyaaf2 tries to keep error checking to a minimum. It checks that the required properties for a class are set and properties obey the typedefs of data model in the file.  It does gives low level access to the underlying Compound File Binary, it should let you shoot your self in the foot more the the aaf sdk or Maj.

I think the thing above would still error in pyaaf2 but it does allows you to add the missing enumeration element to the data model if you know what your are doing. That being said, pyaaf2 does have a lot of the avid extensions [built in](https://github.com/markreidvfx/pyaaf2/blob/master/aaf2/model/ext/typedefs.py#L117) so maybe it will give you less friction there.

**Comment by mrlimbic** [comment]
Thanks. I'll put some time in and give it a go when I get the chance.

**Comment by mrlimbic** [comment]
Did a little more testing. Logic AAFs contain bad dates which pyaaf2 doesn't like.

How would I go about trappping this and just set value to None for any properties that can't be parsed properly?

```
Traceback (most recent call last):
  File "examples/aafdump.py", line 11, in <module>
    f.dump()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyaaf2-1.4.0-py3.8.egg/aaf2/file.py", line 337, in dump
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyaaf2-1.4.0-py3.8.egg/aaf2/core.py", line 368, in dump
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyaaf2-1.4.0-py3.8.egg/aaf2/core.py", line 386, in dump
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyaaf2-1.4.0-py3.8.egg/aaf2/properties.py", line 145, in value
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyaaf2-1.4.0-py3.8.egg/aaf2/types.py", line 605, in decode
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyaaf2-1.4.0-py3.8.egg/aaf2/types.py", line 619, in decode
ValueError: year 0 is out of range
```

**Comment by markreidvfx** [comment]
That should be easy to fix, are you able to provide a sample? The datetime convenience conversion there could be just wrapped with a try.

**Comment by mrlimbic** [comment]
Bad dates are only one possible issue. I've come across many incorrectly specified values in AAFs. A more versatile solution would be to have a strict vs tolerant mode. In tolerant mode any property with bad value gets set to None and a message is added to a report that can be retrieved.

Sample Logic AAF with bad dates.
https://drive.google.com/file/d/1kaFQDJG88n4RMSXnGgFufWw6RRqwdGvm/view?usp=sharing

**Comment by markreidvfx** [comment]
Should be fixed in 7eef0dd38afd0e6888c9c1b6680e5b98f8c59ada
This specific error might because by a bug in 1.1.0 and 1.0.2 of the AAF SDK. 
https://sourceforge.net/p/aaf/bugs/90/
The file says its written with 1.1.0

If you have any other badly structured aafs, feel free to share

**Comment by mrlimbic** [comment]
Thanks. There's a few more I could post. But edge cases come pretty often. More than I'd like. Most apps are bad.

Isn't there a better way though? Not worth firefighting every edge case for every value. 

How about a tolerant mode for property settings?

**Comment by markreidvfx** [comment]
It is not an easy thing to add without knowledge of the edge cases and what specific apps prefer.  We need know what to be more tolerant of first in order to implement some sort of tolerant mode. It would be great if you could share some of the edge case you've found! :)
