### ISSUE TITLE
Modifying "Tape" metadata

### ISSUE THREAD

**Issue by groucho86** [markreidvfx/pyaaf2#9]
Hello,
Could you please provide an example on how to to modify the "Tape" (or "Source File") metadata of assets within a pre-existing AAF?

Thank you very much for this impressive tool!

**Comment by markreidvfx** [comment]
The  tape name is the SourceMob.name a SourceMob that has a TapeDescriptor set in SourceMob.descriptor.  simply changing the name of this mob should change the name of the tape. I don't know how this effects MC if the mob's umid already exists in its internal databases.
