### ISSUE TITLE
Export video essence?

### ISSUE THREAD

**Issue by ginwakeup** [markreidvfx/pyaaf2#91]
Hi,
does pyaaf2 offer a way to export video essence from an aaf file?
I found the SourceMob containing the video essence, but nothing to export it like I could with audio.

Thanks.

**Comment by ginwakeup** [comment]
Closing this as I just solved getting the stream data as bytes and writing it down.
Not sure if this will create me some other problems but I will verify it.

**Comment by markreidvfx** [comment]
If the embedded data is dnxhd, you can write the data to a file and put that ext on your file and ffmpeg should be able to read it.

**Comment by ginwakeup** [comment]
Hey @markreidvfx thanks for the reply. Do you know if I can check if the data is dnxhd from pyaaf2? Is it stored somewhere in the descriptor?
Apparently just writing binaries to a .mov file did the trick anyway, but it's changing my fps from 60 to 25.

**Comment by markreidvfx** [comment]
https://github.com/markreidvfx/pyaaf2/blob/master/aaf2/mobs.py#L318

Yes the CodecDefinition on the descriptor on the sourceMob tells you the codec and the SampleRate is the frame rate.

Changing the ext to mov doesn't make the data a mov file. The data embedded is a raw stream of dnxhd encoded frames back to back.  ffmpeg doesn't rely on the file ext alone is using its probing system correctly identify the file data. A dnxhd frame does not include framerate so ffmpeg needs to be told what is, you need to do this before the -i arg I believe or else it will use the default 25fps

**Comment by ginwakeup** [comment]
@markreidvfx  thanks for the reply, I solved it writing the bytes to a file, reading them back and rewriting them using cv2, so I can specify the fps. Thank you!
