### ISSUE TITLE
How to fill resolutionID when generating a AAF file

### ISSUE THREAD

**Issue by daniel0621** [markreidvfx/pyaaf2#94]
Hello,
I generate an AAF from a mxf file. My AAF file could not play in Avid newscutter if i don't fill resolutionID(= 4073) in CDCIDescriptor. 
i fill resolutionID as 4073 because NewsCutter set it as 4073 when generating the same mxf to an AAF file. But this mxf file doesn't provide the resolutionId field! If any information about resolutionID in mxf and i don't know?

i know resolutionID = 4073 means XDCAM HD 50Mbit(1080i/60). But where is the mapping table?
thanks!

**Comment by markreidvfx** [comment]
Are you able to provide a sample MXF file? MXFdump from [bmx-libmxf](https://sourceforge.net/p/bmxlib/libmxf/ci/master/tree/) might help find the metadata.

**Comment by daniel0621** [comment]
I found the resolutionID in mxf op1a so I can populate it when building the aaf archive. thanks!

**Comment by markreidvfx** [comment]
The mxf parser in pyaaf should be able to find that too now that I think about it. https://github.com/markreidvfx/pyaaf2/blob/main/src/aaf2/mxf.py#L170
